import { Rune } from '@/types/rune';

export const RUNES: Rune[] = [
  {
    id: 'ansuz',
    name: 'Ansuz',
    character: 'ᚨ',
    latinEquivalent: 'A',
    meaning: 'Ancestor, God, Deity',
    keywords: ['wisdom', 'communication', 'divine', 'order'],
    symbolicInterpretation: 'Represents divine wisdom, ancestral guidance, and the breath of life. Associated with Odin and spiritual awakening.',
    etymology: 'From Proto-Germanic *ansuz (god, deity)',
  },
  {
    id: 'berkana',
    name: 'Berkana',
    character: 'ᛒ',
    latinEquivalent: 'B',
    meaning: 'Birch tree, Growth, Fertility',
    keywords: ['growth', 'fertility', 'healing', 'new beginning'],
    symbolicInterpretation: 'Symbol of new beginnings, healing, and feminine power. The birch tree represents resilience and adaptability.',
    etymology: 'From Proto-Germanic *berkōn (birch)',
  },
  {
    id: 'dagaz',
    name: 'Dagaz',
    character: 'ᛞ',
    latinEquivalent: 'D',
    meaning: 'Day, Daybreak, Transformation',
    keywords: ['awakening', 'breakthrough', 'clarity', 'transition'],
    symbolicInterpretation: 'Represents the moment of breakthrough, clarity, and the passage from darkness to light. Marks transformative change.',
    etymology: 'From Proto-Germanic *dagaz (day)',
  },
  {
    id: 'ehwaz',
    name: 'Ehwaz',
    character: 'ᛖ',
    latinEquivalent: 'E',
    meaning: 'Horse, Journey, Movement',
    keywords: ['journey', 'movement', 'partnership', 'progress'],
    symbolicInterpretation: 'Symbol of movement and progress. Represents the partnership between rider and horse, union of opposites.',
    etymology: 'From Proto-Germanic *ehwaz (horse)',
  },
  {
    id: 'fehu',
    name: 'Fehu',
    character: 'ᚠ',
    latinEquivalent: 'F',
    meaning: 'Cattle, Wealth, Property',
    keywords: ['abundance', 'wealth', 'prosperity', 'creation'],
    symbolicInterpretation: 'Represents material wealth and abundance. In ancient times, cattle were the measure of wealth and status.',
    etymology: 'From Proto-Germanic *fehu (cattle, livestock)',
  },
  {
    id: 'gebo',
    name: 'Gebo',
    character: 'ᚷ',
    latinEquivalent: 'G',
    meaning: 'Gift, Exchange, Partnership',
    keywords: ['partnership', 'exchange', 'reciprocity', 'generosity'],
    symbolicInterpretation: 'Symbol of exchange and gift-giving. Represents the bonds created through generosity and mutual obligation.',
    etymology: 'From Proto-Germanic *gebą (gift)',
  },
  {
    id: 'hagalaz',
    name: 'Hagalaz',
    character: 'ᚼ',
    latinEquivalent: 'H',
    meaning: 'Hail, Disruption, Wholeness',
    keywords: ['disruption', 'challenge', 'completion', 'protection'],
    symbolicInterpretation: 'Represents disruption and challenge, yet also wholeness. Like hail that destroys and nourishes, it brings transformation.',
    etymology: 'From Proto-Germanic *hagulaz (hail)',
  },
  {
    id: 'isa',
    name: 'Isa',
    character: 'ᛁ',
    latinEquivalent: 'I',
    meaning: 'Ice, Standstill, Ego',
    keywords: ['stillness', 'ego', 'clarity', 'reflection'],
    symbolicInterpretation: 'Represents standstill and introspection. Ice is hard and clear, symbolizing crystalline focus and self-awareness.',
    etymology: 'From Proto-Germanic *īsą (ice)',
  },
  {
    id: 'jera',
    name: 'Jera',
    character: 'ᛃ',
    latinEquivalent: 'J/Y',
    meaning: 'Year, Harvest, Cycle',
    keywords: ['harvest', 'reward', 'cycle', 'time'],
    symbolicInterpretation: 'Represents the turning of the year and the harvest. Symbol of natural cycles and the rewards of patience.',
    etymology: 'From Proto-Germanic *jeraz (year)',
  },
  {
    id: 'kenaz',
    name: 'Kenaz',
    character: 'ᚲ',
    latinEquivalent: 'K',
    meaning: 'Torch, Knowledge, Craftsmanship',
    keywords: ['knowledge', 'creativity', 'opening', 'illumination'],
    symbolicInterpretation: 'Symbol of the torch and knowledge. Represents illumination, learning, and mastery of skills.',
    etymology: 'From Proto-Germanic *ken(n)aną (to know)',
  },
  {
    id: 'laguz',
    name: 'Laguz',
    character: 'ᛚ',
    latinEquivalent: 'L',
    meaning: 'Water, Flow, Intuition',
    keywords: ['flow', 'intuition', 'emotions', 'healing'],
    symbolicInterpretation: 'Represents water and intuition. Like a lake, it reflects inner truths and emotional depth.',
    etymology: 'From Proto-Germanic *laguz (water, lake)',
  },
  {
    id: 'mannaz',
    name: 'Mannaz',
    character: 'ᛘ',
    latinEquivalent: 'M',
    meaning: 'Man, Humanity, Self',
    keywords: ['humanity', 'selfhood', 'intelligence', 'community'],
    symbolicInterpretation: 'Represents humanity and the self. Symbol of human potential, intelligence, and social bonds.',
    etymology: 'From Proto-Germanic *mannaz (man, human)',
  },
  {
    id: 'nauthiz',
    name: 'Nauthiz',
    character: 'ᚾ',
    latinEquivalent: 'N',
    meaning: 'Need, Constraint, Survival',
    keywords: ['necessity', 'strength', 'constraint', 'friction'],
    symbolicInterpretation: 'Represents necessity and hardship. Through need arises strength; friction creates fire.',
    etymology: 'From Proto-Germanic *naudiz (need, necessity)',
  },
  {
    id: 'othala',
    name: 'Othala',
    character: 'ᛟ',
    latinEquivalent: 'O',
    meaning: 'Homeland, Inheritance, Property',
    keywords: ['inheritance', 'homeland', 'tradition', 'belonging'],
    symbolicInterpretation: 'Symbol of home, homeland, and ancestral inheritance. Represents roots and family legacy.',
    etymology: 'From Proto-Germanic *ōþelą (property, estate)',
  },
  {
    id: 'pertho',
    name: 'Pertho',
    character: 'ᛈ',
    latinEquivalent: 'P',
    meaning: 'Dice, Lot, Mystery',
    keywords: ['mystery', 'chance', 'secrets', 'hidden knowledge'],
    symbolicInterpretation: 'Represents the unknowable and hidden knowledge. Like dice, it symbolizes chance and hidden forces.',
    etymology: 'From Proto-Germanic *perþą (dice cup)',
  },
  {
    id: 'raido',
    name: 'Raido',
    character: 'ᚱ',
    latinEquivalent: 'R',
    meaning: 'Journey, Ride, Communication',
    keywords: ['journey', 'communication', 'harmony', 'flow'],
    symbolicInterpretation: 'Symbol of journeys and communication. Represents the flow of energy and the paths we travel.',
    etymology: 'From Proto-Germanic *raidą (ride, journey)',
  },
  {
    id: 'sowilo',
    name: 'Sowilo',
    character: 'ᛊ',
    latinEquivalent: 'S',
    meaning: 'Sun, Success, Wholeness',
    keywords: ['success', 'vitality', 'wholeness', 'power'],
    symbolicInterpretation: 'Symbol of the sun and its life-giving power. Represents success, vitality, and personal power.',
    etymology: 'From Proto-Germanic *saulō (sun)',
  },
  {
    id: 'tiwaz',
    name: 'Tiwaz',
    character: 'ᛏ',
    latinEquivalent: 'T',
    meaning: 'Warrior, God of War, Justice',
    keywords: ['justice', 'warrior', 'courage', 'conflict'],
    symbolicInterpretation: 'Named after the war god Tiwaz. Represents justice, conflict, and the warrior spirit.',
    etymology: 'From Proto-Germanic *Tīwaz (god of war and justice)',
  },
  {
    id: 'uruz',
    name: 'Uruz',
    character: 'ᚢ',
    latinEquivalent: 'U',
    meaning: 'Aurochs, Strength, Virility',
    keywords: ['strength', 'courage', 'wildness', 'primal power'],
    symbolicInterpretation: 'Symbol of the aurochs, an ancient wild ox. Represents raw power, primal energy, and survival.',
    etymology: 'From Proto-Germanic *ūruz (aurochs)',
  },
  {
    id: 'wunjo',
    name: 'Wunjo',
    character: 'ᚹ',
    latinEquivalent: 'W/V',
    meaning: 'Joy, Comfort, Fellowship',
    keywords: ['joy', 'comfort', 'fellowship', 'harmony'],
    symbolicInterpretation: 'Symbol of joy and harmony. Represents community, friendship, and the warmth of fellowship.',
    etymology: 'From Proto-Germanic *wunjōn (joy, satisfaction)',
  },
  {
    id: 'thurisaz',
    name: 'Thurisaz',
    character: 'ᚦ',
    latinEquivalent: 'Th',
    meaning: 'Giant, Thor, Resistance',
    keywords: ['resistance', 'protection', 'giants', 'conflict'],
    symbolicInterpretation: 'Named after Thor and the giants. Represents resistance, protection, and powerful forces.',
    etymology: 'From Proto-Germanic *þurisaz (giant, demon)',
  },
  {
    id: 'perthro',
    name: 'Perthro',
    character: 'ᛈ',
    latinEquivalent: 'P',
    meaning: 'Dice Cup, Fate, Secrets',
    keywords: ['fate', 'secrets', 'mystery', 'chance'],
    symbolicInterpretation: 'Represents hidden things and the unknown. Connected to fate and the unseen forces of life.',
    etymology: 'From Proto-Germanic *perþą (dice, lot)',
  },
  {
    id: 'algiz',
    name: 'Algiz',
    character: 'ᛉ',
    latinEquivalent: 'Z/X',
    meaning: 'Elk, Protection, Defense',
    keywords: ['protection', 'defense', 'awareness', 'shield'],
    symbolicInterpretation: 'Symbol of the elk and its horns. Represents protection and the shield against adversity.',
    etymology: 'From Proto-Germanic *algiz (elk, protection)',
  },
  {
    id: 'eihwaz',
    name: 'Eihwaz',
    character: 'ᛇ',
    latinEquivalent: 'Ei',
    meaning: 'Yew Tree, Endurance, Transformation',
    keywords: ['endurance', 'transformation', 'death', 'rebirth'],
    symbolicInterpretation: 'Symbol of the yew tree, which can live for thousands of years. Represents transformation through death and rebirth.',
    etymology: 'From Proto-Germanic *īhwaz (yew)',
  },
];

export const runeMap: Record<string, string> = RUNES.reduce(
  (acc, rune) => {
    acc[rune.latinEquivalent.toUpperCase()] = rune.character;
    return acc;
  },
  {} as Record<string, string>
);
